server:
  port: 8080

management:
  port: 9090
  security:
    enabled: false

spring:
  application:
    name: cassandra-simple
    description: Basic Demo to Work with Cassandra.
  data:
    cassandra:
      keyspace-a:
        compression: SNAPPY
        contact-points: localhost
        keyspace-name: sensor_demo_a
      keyspace-b:
        compression: SNAPPY
        contact-points: localhost
        keyspace-name: sensor_demo_b

endpoints:
  health:
    sensitive: false
  metrics:
    sensitive: false
  mappings:
    sensitive: false
  logfile:
    enabled: true
    path: /logfile
    sensitive: false